development:
  database: collection
  adapter: mysql2
  host: 127.0.0.1
  port: 8889
  username: root
  password: root
  encoding: utf8



test:
  adapter: mysql2
  database: collection_test
  username: root
  password: root
  host: 127.0.0.1
  encoding: utf8
  port: 8889



production:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000
